{

   "data_path": "/p/project/hai_verite/training_repository/data/les_faits/final/les_faits",
   
   "save": "/p/project/hai_verite/training_repository/artefacts/checkpoints/160M_GPT-Verite",
   "load": "/p/project/hai_verite/training_repository/artefacts/checkpoints/160M_GPT-Verite",
   

   "vocab-file": "/p/project/hai_verite/training_repository/artefacts/tokenizer/gpt-verite_tokenizer.json",
   "tokenizer_type": "HFTokenizer",

   "pipe-parallel-size": 0,
   "model-parallel-size": 1,


   "train_micro_batch_size_per_gpu": 32,
   "gradient_accumulation_steps": 4,
   "data-impl": "mmap",
   "split": "999,1,0",


   "num-layers": 18, #22
   "hidden-size": 672, #576
   "num-attention-heads": 12, # -> 176M -> 20, 672 | 165M -> 18, 672
   "seq-length": 2048,
   "max-position-embeddings": 2048,
   "norm": "layernorm",
   "pos_emb": rotary,
   "rotary_pct": 0.25,
   "no_weight_tying": true,
   "gpt_j_residual": true,
   "output_layer_parallelism": "column",
   
   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": true,

   "attention_config": [[["flash"], 18]],

   # init methods
   #"init_method": "small_init",
   #"output_layer_init_method": "wang_init",

   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8
     }
   },
   "min_lr": 0.00006,


   "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },


   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   # precision settings
   "precision": "bfloat16",
   "fp32_allreduce": true,

   "train-iters": 49304,
   "lr-decay-iters": 49304,
   "lr-decay-style": "cosine",
   "warmup": 0.01,

   "distributed-backend": "nccl",
   "checkpoint-factor": 5000,
   "eval-interval": 1000,
   "eval-iters": 10,
   "log-interval": 10,
   "steps_per_print": 1,

   "use_wandb": true,
   "wandb_project": "GPT-Verite",
   "wandb_group": "160M_GPT-Verite",

   "keep-last-n-checkpoints": 4,

   "exit_interval": 1435
}
