{

   "data_path": "/pfs/work7/workspace/scratch/ukmwn-les_faits/les_faits_final/hp_sweep_ds/v2/merged/HP_Sweep",
   
   

   "vocab-file": "/home/kit/stud/ukmwn/master_thesis/data/les_faits/tokenizer/gpt-ver-tokenizer.json",
   "tokenizer_type": "HFTokenizer",

   "pipe-parallel-size": 0,
   "model-parallel-size": 1,


   "train_micro_batch_size_per_gpu": 24,
   "gradient_accumulation_steps": 8,
   "data-impl": "mmap",
   "split": "1000,0,0",


   "num-layers": 38,
   "hidden-size": 1664,
   "num-attention-heads": 16,
   "seq-length": 2048,
   "max-position-embeddings": 2048,
   "pos-emb": "rotary",
   "rotary-pct": 0.25,
   "no-weight-tying": true,
   "gpt-j-residual": true,
   "output-layer-parallelism": "column",

   "attention_config": [[["flash"], 38]],
   "scaled_upper_triang_masked_softmax_fusion": true,
   "bias_gelu_fusion": true,
   
   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8
     }
   },
   "min_lr": 0.0006,


   "init_method": "scaled_normal",
   "init_method_std": 0.02,

   "use-mup": false,
   "save-base-shapes": false,   # this only needs to be enabled once in order to generate the base-shapes-file on each rank
   "base-shapes-file": "/home/kit/stud/ukmwn/master_thesis/gpt-verite_/configs/gpt-verite/1-4B_OPT_base_shapes/", # # load base shapes from this file
   "coord-check": false, # generate coord check plots to verify mup's implementation in neox

   "mup-init-scale": 1.0,
   "mup-attn-temp": 1.0,
   "mup-output-temp": 1.0,
   "mup-embedding-mult": 10.0,
   "mup-rp-embedding-mult": 1.0,

   "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },

   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0.0,
   "attention-dropout": 0.0,

   # precision settings
   "bf16": {
    "enabled": true,
  },
   "fp16": {
     "enabled": false,
     "type": "bfloat16", # set bf16 as precision
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "hysteresis": 2,
     "min_loss_scale": 1,
     "initial_scale_power": 12
   },
   "fp32_allreduce": True,

   "train-iters": 986,
   "lr-decay-iters": 986,
   "distributed-backend": "nccl",
   "lr-decay-style": "linear",
   "warmup": 0.01,
   "checkpoint-factor": 2000,
   "eval-interval": 1000,
   "eval-iters": 10,
   "log-interval": 1,
   "steps_per_print": 1,

   "use_wandb": true,
   "wandb_project": "GPT-Verite",
   "wandb_group": "1.4B-GPT-Verite",

   "keep-last-n-checkpoints": 4,
   "wall_clock_breakdown": true,

   "exit_interval": 1500
}
