{

   "data_path": "/pfs/work7/workspace/scratch/ukmwn-les_faits/les_faits_final/entity_tokenizer/merged/LF_ET",
   
   "save": "/home/kit/stud/ukmwn/master_thesis/weights/125m_padding_v1_ET",
   "load": "/home/kit/stud/ukmwn/master_thesis/weights/125m_padding_v1_ET",
   

   "vocab-file": "/pfs/work7/workspace/scratch/ukmwn-les_faits/trained_tokenizers/gpt-verite_entity_tokenizer/tokenizer.json",
   "tokenizer_type": "HFTokenizer",

   "pipe-parallel-size": 0,
   "model-parallel-size": 1,


   "train_micro_batch_size_per_gpu": 32,
   "gradient_accumulation_steps": 4,
   "data-impl": "mmap",
   "split": "1000,0,0",


   "num-layers": 12,
   "hidden-size": 768,
   "num-attention-heads": 12,
   "seq-length": 2048,
   "max-position-embeddings": 2048,
   "norm": "layernorm",
   "pos_emb": rotary,
   "rotary_pct": 0.25,
   "no_weight_tying": true,
   "gpt_j_residual": true,
   "output_layer_parallelism": "column",
   
   "scaled-upper-triang-masked-softmax-fusion": true,
   "bias-gelu-fusion": true,


   # init methods
   "init_method": "small_init",
   "output_layer_init_method": "wang_init",

   "optimizer": {
     "type": "Adam",
     "params": {
       "lr": 0.0006,
       "betas": [0.9, 0.95],
       "eps": 1.0e-8
     }
   },
   "min_lr": 0.00006,


   "zero_optimization": {
    "stage": 0,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },



   "checkpoint-activations": true,
   "checkpoint-num-layers": 1,
   "partition-activations": true,
   "synchronize-each-layer": true,

   "gradient_clipping": 1.0,
   "weight-decay": 0.1,
   "hidden-dropout": 0,
   "attention-dropout": 0,

   "fp16": {
    "fp16": true,
     "enabled": true,
     "loss_scale": 0,
     "loss_scale_window": 1000,
     "initial_scale_power": 12,
     "hysteresis": 2,
     "min_loss_scale": 1
   },

   "train-iters": 49744,
   "lr-decay-iters": 49744,
   "distributed-backend": "nccl",
   "lr-decay-style": "cosine",
   "warmup": 0.01,
   "checkpoint-factor": 2000,
   "eval-interval": 1000,
   "eval-iters": 10,
   
   "log-interval": 100,
   "steps_per_print": 10,
   "wall_clock_breakdown": true,

   "use_wandb": true,
   "wandb_project": "GPT-Verite",
   "wandb_group": "125M_padding_v1_ET",

   "keep-last-n-checkpoints": 4,

   "exit_interval": 895
}
